spring:
  datasource:
    url: jdbc:mysql://161.117.15.122:3306/sb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-init-sqls: set names utf8mb4;
      initialSize: 1
      minIdle: 10
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
      # 配置日志输出
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

  # 也可以通过这种方式 单独配置 某个类的返回结果 @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
  jackson:
#    date-format: yyyy-MM-dd
#    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  # redis 配置
  redis:
    database: 15
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000ms
    jedis:
      pool:
        max-active: 500 # 最大连接数
        max-wait: 3000ms # 最大阻塞时间（负数表示没限制）
        max-idle: 100 # 最大空闲
        min-idle: 1 # 最小空闲



mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 9000
